CREATE TABLE LOGIN (
    ID    INTEGER NOT NULL PRIMARY KEY,
    ATIVO INTEGER NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    SENHA VARCHAR(250) NOT NULL
);

CREATE TABLE PESSOA (
    ID        INTEGER NOT NULL PRIMARY KEY,
    ATIVO     INTEGER NOT NULL,
    NOME      VARCHAR(60) NOT NULL,
    DOCUMENTO VARCHAR(60)
);

CREATE TABLE PESSOA_FOTO_BASE64 (
    ID          INTEGER NOT NULL PRIMARY KEY,
    ID_PESSOA   INTEGER NOT NULL REFERENCES PESSOA (ID) ON DELETE CASCADE,
    FOTO_BASE64 BLOB SUB_TYPE TEXT
);

CREATE TABLE PESSOA_FOTO_BINARY (
    ID           INTEGER NOT NULL PRIMARY KEY,
    ID_PESSOA    INTEGER NOT NULL REFERENCES PESSOA (ID) ON DELETE CASCADE,
    FOTO_BINARY  BLOB SUB_TYPE BINARY,
    NOME_ARQUIVO VARCHAR(255),
    EXTENSAO     VARCHAR(10)
);